### ISSUE TITLE
Player dismiss on opening notification bar

### ISSUE THREAD

**Issue by sachinsardana** [DominikButz/MinimizableView#6]
On playing any music and opening notification bar from anywhere in app it dismiss player window and miniplayer.

**Comment by DominikButz** [comment]
That's too unspecific, you need to send much more information, e.g. a link to a screen video.

**Comment by sachinsardana** [comment]
Please check video

https://user-images.githubusercontent.com/56502185/189669850-3ce50355-ae9d-49c8-a948-bdf129c38b7c.mp4

**Comment by DominikButz** [comment]
sorry, I don't get it. Can you reproduce the issue with a new test project and send it as zip file to me?

**Comment by DominikButz** [comment]
ok, now  I get it. I can't reproduce it - you can check out the example project, it doesn't happen. I use it in an app and I just tried it out on my iPhone, also doesn't happen. Maybe you can create a test project to reproduce the issue.

**Comment by sachinsardana** [comment]
Faced this this issue everytime on iPhone 11 and sometimes on other devices also.

**Comment by DominikButz** [comment]
The problem is I don't know how your app works, so I can't reproduce it. In the app where I use MiniView, this problem never occurred. I tried it in the iPhone 11 simulator but I still can't reproduce it. presentation state depends on the isPresented published variable in the MiniViewModel class. Where do you instantiate the MinimizableViewHandler? It should be instantiated as ObservedObject in the root view of your app and then passed as environmentObject down the view hierarchy.

**Comment by sachinsardana** [comment]
Yes Following same steps as you mentioned
Root Class-> @ObservedObject var miniHandler: MinimizableViewHandler = MinimizableViewHandler()
View-> @EnvironmentObject var miniHandler: MinimizableViewHandler

Issue is on real device not on simulator.

**Comment by DominikButz** [comment]
This is on iPhone 13 mini - the problem does not occur. Create a new project that shows the issue and send it to me, so I can try it hands on. 

https://user-images.githubusercontent.com/5699871/189866620-60b57eef-1db9-4e84-a055-50d7c61bb96f.mov

**Comment by DominikButz** [comment]
closed
